- name: Set ssh setting for connect to github
  copy: src=config dest=~/.ssh/config mode=600

- name: Deploy private key
  copy: src={{ private_key_path }} dest=~/.ssh/github_id_rsa mode=600

- name: Create directory
  sudo: yes
  file: path=/var/www state=directory owner=ec2-user

- name: Set env file for application data
  sudo: yes
  copy: src=environmental_variables.sh dest=/etc/profile.d mode=0775
