- name: install nginx
  yum: name=nginx state=present
  sudo: yes

- name: auto start
  command: chkconfig nginx on
  sudo: yes

- name: start nginx
  command: service nginx restart
  sudo: yes

- name: apply nginx setting.
  template: src="rails_app.conf" dest="/etc/nginx/conf.d/app.conf"
  sudo: yes
